properties:
  iteration_limit: 100
  return_first: true
  time_limit: 120
  C: 1.4
  cutoff_cumulative: 0.999
  cutoff_number: 50
  max_transforms: 8
policy:
  files:
    uspto:
      - ./uspto_model.hdf5
      - ./uspto_templates.hdf5
filter:
  files:
    uspto: ./uspto_filter_model.hdf5
stock:
  files:
    zinc: ./zinc_stock.hdf5
